import asyncio
import bcrypt
from sqlalchemy.future import select
from database import SessionLocal
from models.school import School
from models.user import User

def get_password_hash(password: str) -> str:
    """
    Hashes a plain text password using bcrypt directly.
    This avoids unmaintained passlib compatibility bugs.
    """
    password_bytes = password.encode('utf-8')
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(password_bytes, salt)
    return hashed.decode('utf-8')

async def seed_data():
    """
    Connects to the database and seeds one test school
    and one school admin user if they don't already exist.
    """
    async with SessionLocal() as session:
        async with session.begin():
            # 1. Check if a test school already exists
            result = await session.execute(select(School).filter(School.name == "Test Academy"))
            school = result.scalars().first()
            
            if not school:
                print("Seeding: Creating test school 'Test Academy'...")
                school = School(
                    name="Test Academy",
                    phone="1234567890",
                    exotel_number="01141189359"
                )
                session.add(school)
                # Flush ensures the school.id is generated by the database so we can link the user to it
                await session.flush()
            else:
                print("Seeding: Test school 'Test Academy' already exists.")
                
            # 2. Check if the admin user already exists
            result = await session.execute(select(User).filter(User.email == "admin@example.com"))
            user = result.scalars().first()
            
            if not user:
                print("Seeding: Creating admin user 'admin@example.com' (password: admin123)...")
                hashed_password = get_password_hash("admin123")
                user = User(
                    school_id=school.id,
                    email="admin@example.com",
                    password_hash=hashed_password,
                    role="school_admin",
                    is_active=True
                )
                session.add(user)
            else:
                print("Seeding: Admin user 'admin@example.com' already exists.")

            # 3. Check if the super admin user already exists
            result_sa = await session.execute(select(User).filter(User.email == "superadmin@example.com"))
            super_user = result_sa.scalars().first()

            if not super_user:
                print("Seeding: Creating super admin user 'superadmin@example.com' (password: superpassword123)...")
                hashed_super_password = get_password_hash("superpassword123")
                super_user = User(
                    school_id=None,
                    email="superadmin@example.com",
                    password_hash=hashed_super_password,
                    role="super_admin",
                    is_active=True
                )
                session.add(super_user)
            else:
                print("Seeding: Super admin user 'superadmin@example.com' already exists.")
                
        # Commit all changes to the database
        await session.commit()
    print("Seeding complete!")

if __name__ == "__main__":
    # Run the async seed function
    asyncio.run(seed_data())
