"""add_super_admin_columns_and_nullable_school_id

Revision ID: a7ce07dc19f1
Revises: 34c145b593e5
Create Date: 2026-06-11 23:32:06.172247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ce07dc19f1'
down_revision: Union[str, Sequence[str], None] = '34c145b593e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('city', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('users', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('schools', 'is_active')
    op.drop_column('schools', 'city')
    # ### end Alembic commands ###
